durham_sex.csv durham_age.csv durham_race.csv durham_ethnicity.csv durham_veteran.csv durham_disability.csv client.csv: /script/data_wrangling.py \
 /data/raw/ACSDP5Y2017.DP02_data_with_overlays_2019-11-18T123256.csv \
 /data/raw/ACSDP5Y2017.DP05_data_with_overlays_2019-11-17T201128.csv \
/data/raw/CLIENT_191102.tsv.txt
	python data_wrangling.py
 
 
